version: "3"
services:
  http_mock:
    build: .
    environment:
      - FASTIFY_LOG_LEVEL=error
      - FASTIFY_PRETTY_LOGS=false
      - REDIS_HOST=redis
    volumes:
      - "./src:/home/node/app/src"
    command: bash -c "npx fastify start src/httpmock.js --watch"
    depends_on:
      - redis
    ports:
      - "3333:3000"
  redis:
    image: "redis:alpine"
  adapter:
    build: .
    environment:
      - CORS_ORIGIN=all
      - REDIS_HOST=redis
      
      # local
      # - FASTIFY_LOG_LEVEL=silent
      # - FASTIFY_PRETTY_LOGS=false
      # - SMAUG_URL=http://http_mock:3000/smaug/configuration
      # - FBS_CMS_API_URL=http://http_mock:3000/fbscms
      # - USERINFO_URL=http://http_mock:3000/userinfo     

      # prod
      - FASTIFY_LOG_LEVEL=debug
      - FASTIFY_PRETTY_LOGS=true
      - SMAUG_URL=https://auth-config.dbc.dk/configuration
      - FBS_CMS_API_URL=https://cicero-fbs.com/rest
      - USERINFO_URL=https://login.bib.dk/userinfo
      - HTTPS_PROXY=http://dmzproxy.dbc.dk:3128
      - REDIS_CLUSTER_HOST=frontend-fbscmsadapter-staging-redis-cluster.platform-redis.svc.cloud.dbc.dk

      - |
        FBS_CMS_CREDENTIALS=
        000001,d4383a9fa7214a6d78a019c1328695a3,some-retailerId
        000002,d4383a9fa7214a6d78a019c1328695a3,some-retailerId
        000003,
        000004,d4383a9fa7214a6d78a019c1328695a3
        000005,,some-retailerId,
        ${VALID_FBS_CMS_CREDENTIALS},
        ${VALID_FBS_CMS_CREDENTIALS_2},
        ${VALID_FBS_CMS_CREDENTIALS_3}

      # staging
      # - FBS_CMS_API_URL=https://et.cicero-fbs.com/rest
      
    ports:
      - "3000:3000"
    volumes:
      - "./src:/home/node/app/src"
    depends_on:
      - http_mock
      - redis
    command: bash -c "npx fastify start src/server.js --watch"
