version: "3"
services:
  http_mock:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=info
      - FASTIFY_PRETTY_LOGS=false
      - REDIS_HOST=redis
    command: bash -c "npx fastify start src/httpmock.js --watch"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  adapter:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - SMAUG_URL=http://http_mock:3000/smaug/configuration
      - FBS_CMS_API_URL=http://http_mock:3000/fbscms
      - REDIS_HOST=redis
      - USERINFO_URL=http://http_mock:3000/userinfo
    depends_on:
      - http_mock
      - redis
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:latest
    volumes:
      - "./e2e:/app"
    depends_on:
      - adapter
      - http_mock
    environment:
      - CYPRESS_baseUrl=http://adapter:3000
      - CYPRESS_mockHTTPUrl=http://http_mock:3000
      - CYPRESS_FOLDER=/app/cypress
