version: "3"
services:
  http_mock:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=info
      - FASTIFY_PRETTY_LOGS=false
      - REDIS_HOST=redis
    command: bash -c "npx fastify start src/httpmock.js --watch"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  adapter:
    image: "${IMAGE}"
    environment:
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - SMAUG_URL=http://http_mock:3000/smaug/configuration
      - FBS_CMS_API_URL=http://http_mock:3000/fbscms
      - REDIS_HOST=redis
      - USERINFO_URL=http://http_mock:3000/userinfo

      - |
        FBS_CMS_CREDENTIALS=
        some-agencyid,some-username,some-password,
        some-other-agencyid,some-username,some-password,
        some-random-agencyid,some-username,some-password,
        000001,some-username,some-password,
        000002,some-username,some-password,http://http_mock:3000/some-url,
        000003,
        000004,some-username,
        000005,,some-password,
        
    depends_on:
      - http_mock
      - redis
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:old-202409
    volumes:
      - "./e2e:/app/e2e"
    depends_on:
      - adapter
      - http_mock
    environment:
      - CYPRESS_baseUrl=http://adapter:3000
      - CYPRESS_mockHTTPUrl=http://http_mock:3000
    command: bash -c "npm run cy"
