version: "3"
services:
  http_mock:
    build: .
    environment:
      - FASTIFY_LOG_LEVEL=error
      - FASTIFY_PRETTY_LOGS=false
      - REDIS_HOST=redis
    volumes:
      - "./src:/home/node/app/src"
    command: bash -c "npx fastify start src/httpmock.js --watch"
    depends_on:
      - redis
    ports:
      - "3333:3000"
  redis:
    image: "redis:alpine"
  adapter:
    build: .
    environment:
      - CORS_ORIGIN=all
      - REDIS_HOST=redis
      - REDIS_CLUSTER_HOST=frontend-fbscmsadapter-staging-redis-cluster.platform-redis.svc.cloud.dbc.dk
      - HTTPS_PROXY=http://dmzproxy.dbc.dk:3128

      # local
      - FASTIFY_LOG_LEVEL=silent
      - FASTIFY_PRETTY_LOGS=false
      - SMAUG_URL=http://http_mock:3000/smaug/configuration
      - FBS_CMS_API_URL=http://http_mock:3000/fbscms
      - USERINFO_URL=http://http_mock:3000/userinfo

      # staging
      # - FBS_CMS_API_URL=https://et.cicero-fbs.com/rest

      # prod
      # - FASTIFY_LOG_LEVEL=debug
      # - FASTIFY_PRETTY_LOGS=true
      # - SMAUG_URL=https://auth-config.dbc.dk/configuration
      # - FBS_CMS_API_URL=https://cicero-fbs.com/rest
      # - USERINFO_URL=https://login.bib.dk/userinfo

    ports:
      - "3000:3000"
    volumes:
      - "./src:/home/node/app/src"
    depends_on:
      - http_mock
      - redis
    command: bash -c "npx fastify start src/server.js --watch"
